# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedas',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
